# Generated by Django 2.0.6 on 2018-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
    ]
